name: Build CEF

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

env:
  CEF_BRANCH: 140
  CEF_USE_GN: 1
  CEF_USE_SANDBOX: 1

jobs:
  build-windows64:
    runs-on: windows-latest
    timeout-minutes: 360  # 6小时超时
    env:
      CEF_ARCH: x64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download automate.py
      run: |
        # 直接从 GitHub 下载（更可靠）
        curl -LO "https://raw.githubusercontent.com/chromiumembedded/cef/master/tools/automate/automate.py"
        # 如果失败，尝试 Bitbucket 作为备用
        if (!(Test-Path "automate.py") -or (Get-Item "automate.py").Length -eq 0) {
          curl -LO "https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate.py"
        }

    - name: Run automate.py (最小化构建)
      run: |
        python automate.py --branch=$env:CEF_BRANCH --arch=$env:CEF_ARCH --force-build --minimal-distrib --no-debug-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cef_binary_windows64
        path: code/chromium/src/cef/binary_distrib/*.tar.bz2

  build-linux64:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6小时超时
    env:
      CEF_ARCH: x64
      CEF_USE_SANDBOX: 0  # Linux 上通常禁用沙盒
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl python3 python3-pip

    - name: Download automate.py
      run: |
        curl -LO "https://raw.githubusercontent.com/chromiumembedded/cef/master/tools/automate/automate.py" || \
        curl -LO "https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate.py"

    - name: Run automate.py (最小化构建)
      run: |
        python automate.py --branch=$CEF_BRANCH --arch=$CEF_ARCH --force-build --minimal-distrib --no-debug-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cef_binary_linux64
        path: code/chromium/src/cef/binary_distrib/*.tar.bz2
