name: Build CEF

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日凌晨运行一次（可选）

env:
  CEF_BRANCH: 140  # 使用分支号140对应版本140.1.14
  CEF_USE_GN: 1
  CEF_USE_SANDBOX: 1

jobs:
  build-windows64:
    runs-on: windows-latest
    env:
      CEF_ARCH: x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download automate.py
      run: |
        Invoke-WebRequest -Uri "https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate.py" -OutFile "automate.py"

    - name: Run automate.py on Windows
      run: |
        python automate.py --branch=$env:CEF_BRANCH --arch=$env:CEF_ARCH --use-gn=$env:CEF_USE_GN --use-sandbox=$env:CEF_USE_SANDBOX --force-build --minimal-distrib --client-distrib --no-debug-build

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cef_binary_140_windows64
        path: code/chromium/src/cef/binary_distrib/*.tar.bz2

  build-linux64:
    runs-on: ubuntu-latest
    env:
      CEF_ARCH: x64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget python3 python3-pip npm pkg-config \
          libgtk-3-dev libnss3-dev libxss-dev libasound2-dev libxtst-dev \
          libgbm-dev libgles2-mesa-dev libglu1-mesa-dev

    - name: Download automate.py
      run: |
        wget https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate.py

    - name: Run automate.py on Linux
      run: |
        python automate.py --branch=$CEF_BRANCH --arch=$CEF_ARCH --use-gn=$CEF_USE_GN --use-sandbox=$CEF_USE_SANDBOX --force-build --minimal-distrib --client-distrib --no-debug-build

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cef_binary_140_linux64
        path: code/chromium/src/cef/binary_distrib/*.tar.bz2
