name: CEF Build

on:
  push:
    tags: ['cef_binary_*']
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout CEF
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH

    - name: Run cef_create_projects
      run: cef_create_projects.bat

    - name: Build with Ninja
      run: ninja -C out/Release_GN_x64 cef

    - name: Create distribution
      run: make_distrib.bat --minimal --x64 --no-archive

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cef-windows-binaries
        path: cef_binary_*_distrib/
